# permissions for end users to edit pages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: page-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: webid-operator
    app.kubernetes.io/part-of: webid-operator
    app.kubernetes.io/managed-by: kustomize
  name: page-editor-role
rules:
- apiGroups:
  - webid.golang.betsys.com
  resources:
  - pages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webid.golang.betsys.com
  resources:
  - pages/status
  verbs:
  - get
